name: Deploy Blog to GitHub Pages

on:
  push:
    branches:
      - main  # 每当有内容推送到主分支时触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install marked.js
      run: npm install -g marked
    
    - name: Generate HTML from Markdown
      run: |
        node generateIndex.js
    
    - name: Copy generated index.html to posts folder
      run: cp index.html posts/

    - name: Convert Markdown to HTML
      run: |
        mkdir -p output
        for file in posts/*.md; do
          filename=$(basename "$file" .md)
          marked "$file" > "output/$filename.html"
        done

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git config --global init.defaultBranch 'main'

    - name: Push to GitHub Pages
      env:
        GH_PAT: ${{ secrets.GH_PAT }}  # 使用从 Secrets 中读取的 Token
      run: |
        cd output
        git init
        git remote add origin https://$GH_PAT@github.com/pusong10/pusong10.github.io.git
        git add .
        git commit -m "Update HTML files"
        git push --force --set-upstream origin main